### ISSUE TITLE
Update to emotion 10

### ISSUE THREAD

**Issue by benhinchley** [sajari/sdk-react#93]
Emotion 10 has come out, which has a series of useful features added. 

We should also figure out a way to turn off all styling created by us (leaving all the static CSS classnames) for when people want a clean slate when styling

**Comment by zlatanpham** [comment]
@benhinchley I notice most components from the `sdk` were styled like
```jsx
export const Container = styled("nav")<StyledProps<HTMLElement>>(
  {
    display: "flex",
    justifyContent: "center",
    alignItems: "center"
  },
  override
);
```
as `override` derived from `props.styles`. And the component itself also contains class like `sj-container`. However, the approach has some limitations:
- Users cannot provide custom styles based on the component state. For example: `props => ({ color: props.isDisabled ? "#aaa" : "#777" })`.
- Users cannot use properties from `theme`. For example: `{ color: theme.brand.black }`.
- Provide hardcode classes with prefix like `sj-classname` is needed, but it won't be flexible for all cases. For example, if a site contains 2 paginators with two different styles then we have to write do something like this `.parent-1 .sj-paginator` & `.parent-2 .sj-paginator`.
- There is no way to turn off the default styles rather than overriding them.

I've created a [sandbox](https://codesandbox.io/s/my46rqz7jp), which provides solution for the above problems. Please take a look and let me know what you think?

**Comment by benhinchley** [comment]
@zlatanpham I like this approach, It seems a little cumbersome to have to have a getStyles method on every component, it would be nice to be able to abstract that stuff out into something general, that can be used in `class` and `function` component types

**Comment by zlatanpham** [comment]
@benhinchley, sure you right, `getStyles` should be put inside a HOC for reusable purpose. I've made the update available to check [here](https://codesandbox.io/s/my46rqz7jp).

**Comment by benhinchley** [comment]
@zlatanpham yep like this approach, slot more flexible. On small note in `MyComponent` it seems odd to merge `this.state` and `theme` to be passed into get styles? What's the reasoning behind this?

**Comment by zlatanpham** [comment]
@benhinchley I didn't fully get your point. `state` & `theme` are passed to `getStyles` if they are relevant to changing styles. Just like `emotion` or `styled-components` did:
```jsx
this.state = { active }

const Button = styled('button')(props => (
  {
     backgroundColor: props.active ? props.theme.color.primary : props.theme.color.gray   
  }
))
```

Apparently, the `state` object won't always be fully merged. Sometimes we only need merge the part affecting  the styles or sometimes we don't need to merge `this.state` at all if it's irrelevant to the component styles. The same might go for `theme`.

Or you just meant the `theme` should also be put in `withGetStyles`?

**Comment by benhinchley** [comment]
@zlatanpham no sorry, I get what you are saying, I think i just misread the code the first time. If you want to get started on converting the components over to this new approach that would be awesome

**Comment by zlatanpham** [comment]
Okay, I'll do the update on `Paginator` first and submit a PR for your review. Then, if everything goes well, I'll update the rest.
